### ISSUE TITLE
Could not resolve com.goterl.lazycode:lazysodium-android:5.0.2

### ISSUE THREAD

**Issue by diegomazala** [terl/lazysodium-examples#1]
Hi
I'm trying to build the lazysodium-examples but failing.
I've read the [Getting Started](https://github.com/terl/lazysodium-docs/blob/master/usage/getting-started.md) and [Installation](https://github.com/terl/lazysodium-docs/blob/master/usage/installation.md) pages.
I saw there is a difference in 
`implementation "com.goterl:lazysodium-android:5.0.2@aar"`
` implementation "com.goterl.lazycode:lazysodium-android:5.0.2@aar"`
Not sure which should use. However any of them works of me

When I switch gradle mode offline/online I got this error

Could not GET 'http://dl.bintray.com/terl/lazysodium-maven/com/goterl/lazycode/lazysodium-android/5.0.2/lazysodium-android-5.0.2.pom'. Received status code 403 from server: Forbidden

I will share the gradle files below. 
Any help is very welcome
Thank you very much

Project

```
buildscript {
    repositories {
        google()
        jcenter()
        mavenCentral()
        maven { url "http://dl.bintray.com/terl/lazysodium-maven" }
        maven { url "https://jitpack.io" }
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:4.1.3'
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        google()
        jcenter()
        mavenCentral()
        maven { url "http://dl.bintray.com/terl/lazysodium-maven" }
        maven { url "https://jitpack.io" }
    }
}
task clean(type: Delete) {
    delete rootProject.buildDir
}
```

Module

```
apply plugin: 'com.android.application'

android {
    compileSdkVersion 29
    defaultConfig {
        applicationId "com.goterl.lazycode.lazysodium.example"
        minSdkVersion 19
        targetSdkVersion 29
        multiDexEnabled true
        versionCode 9
        versionName "0.6.0"
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}


dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation "androidx.appcompat:appcompat:1.2.0-beta01"
    implementation "com.google.android.material:material:1.2.0-alpha05"

    testImplementation 'junit:junit:4.12'
    androidTestImplementation('androidx.test.espresso:espresso-core:3.1.0-alpha4', {
        exclude group: 'com.android.support', module: 'support-annotations'
    })



    //implementation "com.goterl:lazysodium-android:5.0.2@aar"
    implementation "com.goterl.lazycode:lazysodium-android:5.0.2@aar"
    implementation "net.java.dev.jna:jna:5.8.0@aar"
    implementation ('com.github.ozodrukh.CircularReveal:circualreveal:2.1.0', {
        transitive = true
        exclude group: 'com.android.support'
    })

    implementation 'com.github.florent37:diagonallayout:1.0.9'
}

```

**Comment by diegomazala** [comment]
In case anyone have this problem.

I had to use

`implementation "com.goterl:lazysodium-android:5.0.2@aar"`
instead of 
`implementation "com.goterl.lazycode:lazysodium-android:5.0.2@aar"`

as in [app gradlle](https://github.com/terl/lazysodium-examples/blob/master/android/app/build.gradle)

Also,  I had to replace all 
`import com.goterl.lazycode.lazysodium`
by
`import com.goterl.lazysodium`

Not sure if this is the correct way but it is working so far

**Comment by gurpreet-** [comment]
This whole examples lib is vastly out of date. Yes, as you've found out, the package ID has changed in version 5.0 and above due to the move to MavenCentral because of JCenter/Bintray being deprecated.

**Comment by gurpreet-** [comment]
Moved the java examples to the Lazysodium Java library

**Comment by BayoKwendo** [comment]
ok still facing this issue yet is closed. Whats the solution

**Comment by olorin3000** [comment]
> ok still facing this issue yet is closed. Whats the solution

Hi, did you find some solution? faced with the same
